export type TranscriptSegment = {
  text: string;
  start: number;
  duration: number;
};

export type StoredTranscript = {
  videoId: string;
  videoUrl: string;
  /** Learning track language (YouTube `lang`). */
  languageCode: string;
  capturedAt: string;
  source: 'ytInitialPlayerResponse' | 'interceptedTimedtextUrl' | 'unknown';
  /** Learning track cues (word-click target). */
  segments: TranscriptSegment[];
  /** Auto-translated native line; index-paired with `segments`. */
  nativeSegments?: TranscriptSegment[];
  /** Semia native language used when fetching `nativeSegments`. */
  nativeLanguageCode?: string;
  /**
   * YouTube `tlang` timedtext failed (e.g. 429). Native line uses GTX instead;
   * any cached `nativeSegments` must be ignored.
   */
  nativeTrackUnavailable?: boolean;
  /** Watch page title without the trailing " - YouTube". */
  title?: string;
  channel?: string;
};

export type WordRef = {
  cueIndex: number;
  wordIndex: number;
};

export type FocusRef = WordRef & {
  text: string;
};

export type SelectionRange = {
  start: WordRef;
  end: WordRef;
};

export type YouTubeAnchor = {
  kind: 'youtube';
  videoId: string;
  selection: SelectionRange;
  focusWord: FocusRef;
  contextCues: TranscriptSegment[];
  contextCueIndices: [number, number];
  startSeconds: number;
  endSeconds: number;
};

/** Reserved for Phase 2 web capture; not written yet. */
export type WebLocateQuality = 'precise' | 'uncertain' | 'degraded';

export type WebAnchor = {
  kind: 'web';
  textQuote: { exact: string; prefix?: string; suffix?: string };
  textPosition: { start: number; end: number };
  /** `precise` when restore is likely; `uncertain` when LaTeX or fuzzy locate. */
  locateQuality: WebLocateQuality;
  /** Set when locateQuality is degraded (legacy captures or future explicit paths). */
  locateFailureReason?: string;
  cssSelector?: string;
};

export type FragmentAnchor = YouTubeAnchor | WebAnchor;

export type SnippetTriageStatus = 'pending' | 'review' | 'mastered';

/** 0 = immediate on first review; 1–4 map to 1d / 3d / 14d / 30d+ */
export type ReviewStage = 0 | 1 | 2 | 3 | 4;

export type FragmentBase = {
  id: string;
  selectedText: string;
  contextText: string;
  languageCode: string;
  sourceUrl: string;
  sourceTitle: string;
  capturedAt: string;
  /** Absent on legacy rows until migrateFragment runs. */
  triageStatus?: SnippetTriageStatus;
  /** Meaningful while triageStatus is review. */
  reviewStage?: ReviewStage;
  dueAt?: string;
  enteredReviewAt?: string;
  lastReviewedAt?: string;
};

export type LanguageFragment = FragmentBase & {
  anchor: FragmentAnchor;
};

/** Pre-refactor flat shape stored in older extension versions. */
export type LegacyLanguageFragment = {
  id: string;
  videoId: string;
  videoUrl: string;
  languageCode: string;
  selectedText: string;
  selection: SelectionRange;
  focusWord: FocusRef;
  contextCues: TranscriptSegment[];
  contextCueIndices: [number, number];
  start: number;
  end: number;
  capturedAt: string;
};

export type CorpusNote = {
  markdown: string;
  updatedAt: string;
};

export type CorpusNotesMap = Record<string, CorpusNote>;

export type SnippetUnitType = 'word' | 'others';

/** Structured note shown on the SEMIA detail card. */
export type SnippetNote = {
  originalSpeech: string;
  naturalTranslation: string;
  /** Bilingual paragraph: original context, then ---, then translation. */
  dynamicContextBlock: string;
  backgroundNote: string;
  /** AI classification: word-level capture vs everything else. */
  unitType?: SnippetUnitType;
  /** Auto-generated bilingual example for word-level captures. */
  illustrativeExample?: string;
  /** @deprecated Migrated to illustrativeExample on read. */
  example?: string;
  /** Present when generated by AI; absent for placeholders. */
  generatedAt?: string;
};

export type SnippetNotesMap = Record<string, SnippetNote>;

export type CardIntent = 'speaking' | 'writing';

export type LanguageCardExample = {
  kind: CardIntent;
  text: string;
  translation: string;
};

/** Max language cards per capture (roadmap: replace My notes sidebar). */
export const MAX_LANGUAGE_CARDS_PER_FRAGMENT = 3;

/** Permanent learner-focused study card linked to a capture. */
export type LanguageCard = {
  id: string;
  sourceFragmentId: string;
  focusText: string;
  intents: CardIntent[];
  focus: string;
  meaning: string;
  scenario?: string;
  dialogue?: string;
  pitfalls?: string;
  personalNote?: string;
  examples: LanguageCardExample[];
  createdAt: string;
  generatedAt: string;
  /** Cards enter review on create; absent on legacy rows until normalizeLanguageCard. */
  triageStatus?: Exclude<SnippetTriageStatus, 'pending'>;
  reviewStage?: ReviewStage;
  dueAt?: string;
  enteredReviewAt?: string;
  lastReviewedAt?: string;
};

export type LanguageCardsMap = Record<string, LanguageCard>;

export type AiProvider = 'deepseek' | 'openai';

export type SemiaSettings = {
  aiProvider?: AiProvider;
  /** Provider API key (DeepSeek or OpenAI depending on aiProvider). */
  aiApiKey?: string;
  /** @deprecated Use aiApiKey. Kept for older saved settings. */
  openAiApiKey?: string;
  /** BCP-47-ish tag used for background explanations, e.g. zh-TW */
  nativeLanguage?: string;
  /** Last chosen YouTube caption learning language (e.g. en). */
  learningLanguage?: string;
  /** When false, overlay shows learning line only. Default: on. */
  bilingualCaptionsEnabled?: boolean;
  /** When false, skip auto context window generation and show a settings hint. Default: on. */
  contextWindowEnabled?: boolean;
  /** Dev/billing stub: allow language card creation when true. */
  languageCardsProEnabled?: boolean;
  /** When false, skip AI suggestions for language card meaning/example. Default: on. */
  languageCardAiSuggestionsEnabled?: boolean;
  /** Optional fields pre-enabled on every new language card draft. */
  languageCardDefaultOptionalFields?: import('./languageCardOptionalFields').LanguageCardOptionalFieldKey[];
  /** @deprecated Unified focus keyword prompt; no longer user-configurable. */
  focusKeywordMode?: 'daily' | 'advanced';
  /** When true, skip the inbox archive confirm when no formal language card exists. */
  skipInboxArchiveWithoutFormalCardConfirm?: boolean;
  /** Cursor deep dark theme for corpus UI. Default: off (light). */
  darkModeEnabled?: boolean;
  /** When true, assistant chat blocks are draggable into language cards. Default: off (read). */
  snippetChatDragModeEnabled?: boolean;
};
