export type TranscriptSegment = {
  text: string;
  start: number;
  duration: number;
};

export type StoredTranscript = {
  videoId: string;
  videoUrl: string;
  languageCode: string;
  capturedAt: string;
  source: 'ytInitialPlayerResponse' | 'interceptedTimedtextUrl' | 'unknown';
  segments: TranscriptSegment[];
};

export type WordRef = {
  cueIndex: number;
  wordIndex: number;
};

export type FocusRef = WordRef & {
  text: string;
};

export type SelectionRange = {
  start: WordRef;
  end: WordRef;
};

export type LanguageFragment = {
  id: string;
  videoId: string;
  videoUrl: string;
  languageCode: string;
  selectedText: string;
  selection: SelectionRange;
  focusWord: FocusRef;
  contextCues: TranscriptSegment[];
  contextCueIndices: [number, number];
  start: number;
  end: number;
  capturedAt: string;
};

export type CorpusNote = {
  markdown: string;
  updatedAt: string;
};

export type CorpusNotesMap = Record<string, CorpusNote>;

/** Structured note shown on the SEMIA detail card. */
export type SnippetNote = {
  originalSpeech: string;
  naturalTranslation: string;
  /** Bilingual paragraph: original context, then ---, then translation. */
  dynamicContextBlock: string;
  backgroundNote: string;
  example: string;
  /** Present when generated by AI; absent for placeholders. */
  generatedAt?: string;
};

export type SnippetNotesMap = Record<string, SnippetNote>;

export type AiProvider = 'deepseek' | 'openai';

export type SemiaSettings = {
  aiProvider?: AiProvider;
  /** Provider API key (DeepSeek or OpenAI depending on aiProvider). */
  aiApiKey?: string;
  /** @deprecated Use aiApiKey. Kept for older saved settings. */
  openAiApiKey?: string;
  /** BCP-47-ish tag used for background explanations, e.g. zh-TW */
  nativeLanguage?: string;
};
