export type TranscriptSegment = {
  text: string;
  start: number;
  duration: number;
};

export type StoredTranscript = {
  videoId: string;
  videoUrl: string;
  languageCode: string;
  capturedAt: string;
  source: 'ytInitialPlayerResponse' | 'interceptedTimedtextUrl' | 'unknown';
  segments: TranscriptSegment[];
  /** Watch page title without the trailing " - YouTube". */
  title?: string;
  channel?: string;
};

export type WordRef = {
  cueIndex: number;
  wordIndex: number;
};

export type FocusRef = WordRef & {
  text: string;
};

export type SelectionRange = {
  start: WordRef;
  end: WordRef;
};

export type YouTubeAnchor = {
  kind: 'youtube';
  videoId: string;
  selection: SelectionRange;
  focusWord: FocusRef;
  contextCues: TranscriptSegment[];
  contextCueIndices: [number, number];
  startSeconds: number;
  endSeconds: number;
};

/** Reserved for Phase 2 web capture; not written yet. */
export type WebLocateQuality = 'precise' | 'uncertain' | 'degraded';

export type WebAnchor = {
  kind: 'web';
  textQuote: { exact: string; prefix?: string; suffix?: string };
  textPosition: { start: number; end: number };
  /** `precise` when restore is likely; `uncertain` when LaTeX or fuzzy locate. */
  locateQuality: WebLocateQuality;
  /** Set when locateQuality is degraded (legacy captures or future explicit paths). */
  locateFailureReason?: string;
  cssSelector?: string;
};

export type FragmentAnchor = YouTubeAnchor | WebAnchor;

export type SnippetTriageStatus = 'pending' | 'review' | 'mastered';

export type FragmentBase = {
  id: string;
  selectedText: string;
  contextText: string;
  languageCode: string;
  sourceUrl: string;
  sourceTitle: string;
  capturedAt: string;
  /** Absent on legacy rows until migrateFragment runs. */
  triageStatus?: SnippetTriageStatus;
};

export type LanguageFragment = FragmentBase & {
  anchor: FragmentAnchor;
};

/** Pre-refactor flat shape stored in older extension versions. */
export type LegacyLanguageFragment = {
  id: string;
  videoId: string;
  videoUrl: string;
  languageCode: string;
  selectedText: string;
  selection: SelectionRange;
  focusWord: FocusRef;
  contextCues: TranscriptSegment[];
  contextCueIndices: [number, number];
  start: number;
  end: number;
  capturedAt: string;
};

export type CorpusNote = {
  markdown: string;
  updatedAt: string;
};

export type CorpusNotesMap = Record<string, CorpusNote>;

/** Structured note shown on the SEMIA detail card. */
export type SnippetNote = {
  originalSpeech: string;
  naturalTranslation: string;
  /** Bilingual paragraph: original context, then ---, then translation. */
  dynamicContextBlock: string;
  backgroundNote: string;
  example: string;
  /** Present when generated by AI; absent for placeholders. */
  generatedAt?: string;
};

export type SnippetNotesMap = Record<string, SnippetNote>;

export type AiProvider = 'deepseek' | 'openai';

export type SemiaSettings = {
  aiProvider?: AiProvider;
  /** Provider API key (DeepSeek or OpenAI depending on aiProvider). */
  aiApiKey?: string;
  /** @deprecated Use aiApiKey. Kept for older saved settings. */
  openAiApiKey?: string;
  /** BCP-47-ish tag used for background explanations, e.g. zh-TW */
  nativeLanguage?: string;
};
