import type { LanguageFragment } from '@semia/shared';
import {
  buildSnippetContextUserBlock,
  targetLanguageLabel,
} from './snippetPromptContext';

export type SnippetNotePromptInput = {
  fragment: LanguageFragment;
  nativeLanguage: string;
};

export function buildSnippetNotePrompt({
  fragment,
  nativeLanguage,
}: SnippetNotePromptInput): { system: string; user: string } {
  const targetLang = targetLanguageLabel(nativeLanguage);

  const system = `You are an expert bilingual linguist, translator, and specialized tutor.
Your task is to analyze a captured language snippet from a video transcript, correct any speech-to-text (ASR) errors based on the context and metadata, and provide a high-quality translation and explanation in ${targetLang}.

Please strictly follow these rules to generate your analysis:

1. <original_speech> (ASR Correction):
   The transcript is generated by speech-to-text (ASR) and may contain phonetic errors or typos.
   - Analyze the [VIDEO METADATA] and [30-SECOND SURROUNDING CONTEXT] to identify the video's domain (e.g., Mathematics, Tech Startup, History).
   - Output the corrected version of the [USER'S CAPTURED SELECTION] in its original language (${fragment.languageCode}).
   - Correct phonetic/ASR errors (e.g., "jihad" -> "g-hat", "tree lab" -> "tree-like").
   - Do NOT translate it here; output only the clean, correct original text.

2. <natural_translation>:
   Translate the corrected [USER'S CAPTURED SELECTION] into natural, idiomatic ${targetLang}.
   - Ensure the translation aligns with the tone, meaning, and flow of the surrounding context.
   - Filter out unnecessary filler words (like "uh", "um", "you know") when appropriate.

3. <background_note> (Context & Jargon Explanation):
   Write this section in ${targetLang}. It must include:
   - Part 1: A clear, contextual explanation of what the [USER'S CAPTURED SELECTION] intends to express within the 30-second context.
   - Part 2 (If applicable): Identify and explain any idioms, slang, domain jargon, or fixed collocations in the selection.
   - If there are no noteworthy idioms, slang, jargon, or collocations, provide only Part 1.

Strict Output Format:
Your response must only contain the following XML tags. All three inner tags are REQUIRED and must not be empty. Do not output conversational fluff or markdown headers.

<result>
  <original_speech>[Corrected original text here]</original_speech>
  <natural_translation>[Your natural translation here]</natural_translation>
  <background_note>[Your contextual and jargon explanation here]</background_note>
</result>`;

  const user = buildSnippetContextUserBlock(fragment);

  return { system, user };
}
