import type { LanguageFragment } from '@semia/shared';
import { isYouTubeAnchor } from '@semia/shared';
import {
  buildSnippetContextUserBlock,
  targetLanguageLabel,
} from './snippetPromptContext';

export type SnippetNotePromptInput = {
  fragment: LanguageFragment;
  nativeLanguage: string;
};

function buildYouTubeSnippetSystemPrompt(
  fragment: LanguageFragment,
  targetLang: string,
): string {
  return `You are an expert bilingual linguist, translator, and specialized tutor.
Your task is to analyze a captured language snippet from a video transcript, correct any speech-to-text (ASR) errors based on the context and metadata, and provide a high-quality translation and explanation in ${targetLang}.

Please strictly follow these rules to generate your analysis:

1. <original_speech> (ASR Correction):
   The transcript is generated by speech-to-text (ASR) and may contain phonetic errors or typos.
   - Analyze the [VIDEO METADATA] and [30-SECOND SURROUNDING CONTEXT] to identify the video's domain (e.g., Mathematics, Tech Startup, History).
   - Output the corrected version of the [USER'S CAPTURED SELECTION] in its original language (${fragment.languageCode}).
   - Correct phonetic/ASR errors (e.g., "jihad" -> "g-hat", "tree lab" -> "tree-like").
   - Do NOT translate it here; output only the clean, correct original text.

2. <natural_translation>:
   Translate the corrected [USER'S CAPTURED SELECTION] into natural, idiomatic ${targetLang}.
   - Ensure the translation aligns with the tone, meaning, and flow of the surrounding context.
   - Filter out unnecessary filler words (like "uh", "um", "you know") when appropriate.

3. <background_note> (Brief Context):
   Write this section in ${targetLang}. Keep it short: **at most 5–6 lines** total.
   - Explain what the selection means in the surrounding context.
   - If one idiom, slang term, or jargon phrase matters, explain it briefly; otherwise skip.
   - Do not repeat the translation or pad with generic commentary.

4. <unit_type> (Capture classification):
   Classify the [USER'S CAPTURED SELECTION] as exactly one value:
   - \`word\` — a single word or very short lexical item the learner might study as vocabulary
   - \`others\` — a phrase, clause, full sentence, or anything else

Strict Output Format:
Your response must only contain the following XML tags. All four inner tags are REQUIRED and must not be empty. Do not output conversational fluff or markdown headers.

<result>
  <original_speech>[Corrected original text here]</original_speech>
  <natural_translation>[Your natural translation here]</natural_translation>
  <background_note>[Your contextual and jargon explanation here]</background_note>
  <unit_type>word|others</unit_type>
</result>`;
}

function buildWebSnippetSystemPrompt(
  fragment: LanguageFragment,
  targetLang: string,
): string {
  return `You are an expert bilingual linguist, translator, and specialized tutor.
Your task is to analyze a captured language snippet from a web page and provide a high-quality translation and explanation in ${targetLang}.

Please strictly follow these rules to generate your analysis:

1. <original_speech>:
   Output the [USER'S CAPTURED SELECTION] in its original language (${fragment.languageCode}).
   - Preserve the exact wording from the page unless it is clearly broken by a line break or OCR artifact.
   - Do NOT translate it here.

2. <natural_translation>:
   Translate the selection into natural, idiomatic ${targetLang}.
   - Ensure the translation aligns with the tone and meaning of the surrounding page context.

3. <background_note> (Brief Context):
   Write this section in ${targetLang}. Keep it short: **at most 5–6 lines** total.
   - Explain what the selection means using [PAGE METADATA] and [PAGE CONTEXT].
   - If one idiom, slang term, or jargon phrase matters, explain it briefly; otherwise skip.
   - Do not repeat the translation or pad with generic commentary.

4. <unit_type> (Capture classification):
   Classify the [USER'S CAPTURED SELECTION] as exactly one value:
   - \`word\` — a single word or very short lexical item the learner might study as vocabulary
   - \`others\` — a phrase, clause, full sentence, or anything else

Strict Output Format:
Your response must only contain the following XML tags. All four inner tags are REQUIRED and must not be empty. Do not output conversational fluff or markdown headers.

<result>
  <original_speech>[Original text here]</original_speech>
  <natural_translation>[Your natural translation here]</natural_translation>
  <background_note>[Your contextual and jargon explanation here]</background_note>
  <unit_type>word|others</unit_type>
</result>`;
}

export function buildSnippetNotePrompt({
  fragment,
  nativeLanguage,
}: SnippetNotePromptInput): { system: string; user: string } {
  const targetLang = targetLanguageLabel(nativeLanguage);
  const system = isYouTubeAnchor(fragment.anchor)
    ? buildYouTubeSnippetSystemPrompt(fragment, targetLang)
    : buildWebSnippetSystemPrompt(fragment, targetLang);
  const user = buildSnippetContextUserBlock(fragment);

  return { system, user };
}
